<?php
/**
 * @file
 * Facebook app helper functions - allows you to figure out if app is in canvas mode and adds a js and css file for canvas specific stuff.
 * Code to determine if user is in Canvas taken from https://github.com/navgarcha/jquery-facebook
 * 
 */

/**
 * Implements hook_perm().
 */
function fb_app_helper_perm() {
  return array();
}

/**
 * Implementation of hook_init().
 */
function fb_app_helper_init() {
  
  drupal_add_js(array(
    'fb_app_helper' => array(
      'path' => drupal_get_path('module', 'fb_app_helper')
    )
  ), 'setting');
  
  _fb_app_helper_add_scripts();
}

function fb_app_helper_menu() {
  $items['admin/settings/fbconnect/helper'] = array(
    'title' => 'FB Helper',
    'description' => 'Configure global settings for FB App Helper.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fb_app_helper_settings_form'),
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}

/**
 * Admin settings form.
 */
function fb_app_helper_settings_form() {
  $form = array();    
  $form['fb_app_helper_active'] = array(
    '#type' => 'checkbox',
    '#title' => t('Activate'),
    '#default_value' => variable_get('fb_app_helper_active', FALSE),
  );
  return system_settings_form($form);
}

/**
* Add CSS and JS Files 
*/
function _fb_app_helper_add_scripts() {
  if(variable_get('fb_app_helper_active', FALSE)) {
    drupal_add_js(drupal_get_path('module', 'fb_app_helper') . '/js/loader.js');  
  }
}
